config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'sitio#inicio'
  get 'acerca' => 'sitio#acerca'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/sitio_controller.rb
class SitioController < ApplicationController
  def inicio
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sitio_helper.rb
module SitioHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="collapsed navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-8" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span> <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="#" class="navbar-brand">Brand</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-8">
      <ul class="nav navbar-nav">
        <li><%= link_to "Inicio", root_path%></a></li>
        <li><%= link_to "Acerca", acerca_path%></a></li>
      </ul>
      <ul class="nav navbar-nav pull-right">
        <li><%= link_to "Iniciar sesión", acerca_path%></a></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CursoRuby</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%=render "layouts/header"%>
    <div class="container-fluid">
      <% flash.each do |name, msg| %>
          <%= content_tag(:div, msg, class: "alert alert-#(name)") %>
      <%end%>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
      <%=render "sitio/footer"%>
    </div>
  </body>
</html>

app/views/sitio/_footer.html.erb
<div class='footer'>
  <small>
    Curso creado por alejandro Carvajal
  </small>
</div>

app/views/sitio/acerca.html.erb
<h1>Curso Ruby on Rails</h1>
<p>
  Acerca de... utilizando framework Ruby on Rails
  <%= link_to "Enlace a Oja.la", "http://oja.la"%>
</p>

app/views/sitio/inicio.html.erb
<div class="row">
  <div class="col-md-4">
    <h2>Barra de navegaci&oacute;n</h2>
  </div>
  <div class="col-md-8">
    <div class="jumbotron">
      <h1>Curso Ruby on Rails</h1>
      <p>
        Ejemplo aplicacion utilizando framework Ruby on Rails
        <%= link_to "Enlace a Oja.la", "http://oja.la"%>
        <%= link_to "Ruby on Rails", "http://rubyonrails.org"%>
      </p>
      <p>
        <%= link_to "Registrarse", "#", :class=> 'btn btn-primary btn-lg' %>
      </p>
    </div>
    </span>
  </div>
</div>